name: Release Build

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

env:
  isReleaseCandidate: ${{ contains(github.ref, 'tags') && contains(github.ref, '-rc') }}
  isFinalRelease: ${{ contains(github.ref, 'tags') && !contains(github.ref, '-rc') }}

jobs:

  secrets-main-wdl:
    runs-on: ubuntu-latest
    outputs:
      ok: ${{ steps.check-secrets.outputs.ok }}
    steps:
      - name: check for secrets MAIN_WDL needed to run the workflow
        id: check-secrets
        run: |
          if [ ! -z "${{ secrets.MAIN_WDL }}" ]; then
            echo "::set-output name=ok::true"
          fi

  release-build:

    runs-on: ubuntu-18.04
    name: Build the release candidate , make pre-release  and publish the artifacts.

    needs:
      - secrets-main-wdl
    if: ${{ needs.secrets-main-wdl.outputs.ok == 'true' }}

    steps:

      - uses: actions/checkout@v2.3.4 # https://github.com/actions/checkout.
        with:
          submodules: recursive
          token: ${{ secrets.PAT_KEY }}
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install the wdl-packager
        run: |
          python -m pip install --upgrade pip
          pip install wdl-packager

      - name: Build the wdl-packager
        with:
          main_workflow: ${{ secrets.MAIN_WDL }}
        run: |
          wdl-packager --reproducible -a LICENSE $main_workflow

      - name: Tags the Main WDL workflow as versioned
        env:
          main_workflow: ${{ secrets.MAIN_WDL }}
        shell: bash
        run: |
          echo "BASE_WDL=$(basename $main_workflow .wdl)" >> $GITHUB_ENV
          echo ${{ env.BASE_WDL }}
          echo "GIT_TAG_LAST=$(git describe --abbrev=0)" >> $GITHUB_ENV
          echo ${{ env.GIT_TAG_LAST }}
      - name: Copy the main workflow as versioned
        env:
          main_workflow: ${{ secrets.MAIN_WDL }}
        run: cp ./$main_workflow ./${{ env.BASE_WDL }}_${{ env.GIT_TAG_LAST }}.wdl

      - name: Build (pre-release)
        if: env.isReleaseCandidate == 'true'
        uses: ncipollo/release-action@v1.8.6
        with:
          token: ${{ secrets.PAT_KEY }}
          prerelease: true
          draft: true
          bodyFile: "RELEASENOTES.md"
          allowUpdates: true
          replacesArtifacts: true
          artifacts: '${{ env.BASE_WDL }}_${{ env.GIT_TAG_LAST }}.wdl,${{ env.BASE_WDL }}_${{ env.GIT_TAG_LAST }}.zip'

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v1
        with:
          path: |
            ${{ env.BASE_WDL }}_${{ env.GIT_TAG_LAST }}.wdl
            ${{ env.BASE_WDL }}_${{ env.GIT_TAG_LAST }}.zip