name: Release Build

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

env:
  isReleaseCandidate: ${{ contains(github.ref, 'tags') && contains(github.ref, '-rc') }}
  isFinalRelease: ${{ contains(github.ref, 'tags') && !contains(github.ref, '-rc') }}

jobs:
  release-build:

    runs-on: ubuntu-18.04
    name: Build the release candidate , make pre-release  and publish the artifacts.

    steps:

      - uses: actions/checkout@v2.3.4 # https://github.com/actions/checkout.
        with:
          submodules: recursive
          token: ${{ secrets.PAT_KEY }}
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install the wdl-packager
        run: |
          python -m pip install --upgrade pip
          pip install wdl-packager

      - name: Build the wdl-packager
        run: |
          wdl-packager --reproducible -a LICENSE  ${{ secrets.MAIN_WDL }}

      - name: Build the wdl-packager
        run: |
          wdl-packager --reproducible -a LICENSE  ${{ secrets.MAIN_WDL }}

      - name: Tags the Main WDL workflow as versioned
        run: |
          export git_last_tag=$(git describe --abbrev=0); echo ${git_last_tag}
          export base_wdl=$(basename ${{ secrets.MAIN_WDL }} .wdl)
          cp ${{ secrets.MAIN_WDL }} ${{ base_wdl }}_${git_last_tag}.wdl

      - name: Build (pre-release)
        if: env.isReleaseCandidate == 'true'
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.PAT_KEY }}
          prerelease: true
          draft: true
          bodyFile: "RELEASENOTES.md"
          allowUpdates: true
          replacesArtifacts: true
          artifacts: '${{ base_wdl }}_${git_last_tag}.wdl,${{ base_wdl }}_${git_last_tag}.zip'

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v1
        with:
          path: |
            ${{ base_wdl }}_${git_last_tag}.wdl
            ${{ base_wdl }}_${git_last_tag}.zip